### ISSUE TITLE
Tails is still shows heads 

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-frontend#139]
![Screenshot_20191223-091136_Chrome](https://user-images.githubusercontent.com/1928801/71345072-98477a80-2564-11ea-8199-cecbbc761e06.jpg)

**Comment by dnaranjo89** [comment]
oh....... one thing....

**Comment by dnaranjo89** [comment]
It's this line, I'll fi it in a moment: https://github.com/etcaterva/eas-frontend/blob/master/src/components/Pages/FlipCoinPage/FlipCoinPage.scss#L63

**Comment by palvarez89** [comment]
Seems to be fixed already. Thanks!
