### ISSUE TITLE
FB raffle nitpicks

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-frontend#155]
Title "Sorte en Facebook"
backspace para borrar
no trailing comma 

"Hay 2 persona inscrita"

FB: `URL bloqueada: La redirección ha fallado porque la URI no está incluida en la lista de autorizados OAuth de cliente de la aplicación. Comprueba que el acceso "OAuth" de cliente y web estén activados y añade todos los dominios de tus aplicaciones como URI de redirección "OAuth"`

**Comment by dnaranjo89** [comment]
all fixed
