### ISSUE TITLE
Allow retrieving and re-tossing quick draws through a URL

### ISSUE THREAD

**Issue by mariocj89** [etcaterva/eas-frontend#174]
When a user creates a draw, he needs to be able to access the draw again with the inputs from the previously created draw. Currently, users have no way to save a draw that was already created to reuse its input.

In the last meeting, it was proposed to display the id in quickdraws with the objective of allowing users to generate new results of an existing draw.

If it is necessary, a new element "quick" can be added to the metadata attribute of the draw to identify them.

**Comment by dnaranjo89** [comment]
This is done already, isn't it?

**Comment by mariocj89** [comment]
yup
