### ISSUE TITLE
Confusing output on facebook raffle

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-frontend#175]
Today is 23th of May:

```
El resultado será publicado el 19 de mayo de 2020 9:13
Los resultados ya se han publicado. Por favor, recarga la página
```

This could be clear that we are waiting for more participants?

**Comment by dnaranjo89** [comment]
yeah that's indeed confusing.... But I guess that the raffle should just be closed without winners, right? 
what do you think @mariocj89?

**Comment by mariocj89** [comment]
Last conversation we had was to wait for the raffle to have participants, we can easily change that. We can make a result invalid or something like that if that's what you mean.

**Comment by palvarez89** [comment]
If the behavior stays, we need to improve that message, that's all.

**Comment by dnaranjo89** [comment]
this is done
