### ISSUE TITLE
Letter generation fails if requesting more than 26 results

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-frontend#178]
Error message:
```
Estamos teniendo problemas en nuestro servidor.

```

Maybe the backend fails? How are we  dealing with this case in eas2 (it doesn't fail)

**Comment by dnaranjo89** [comment]
I'll update the validation message. 
That's one for @mariocj89 too. The backend has a validation rule to avoid requesting more than 27 letter. That would only make sense when "Repeated results" are not allowed.

**Comment by dnaranjo89** [comment]
fix on the client: fa81c6c

**Comment by palvarez89** [comment]
It still fails, even if you allow repeated results :(

**Comment by palvarez89** [comment]
This was done, can't remember how or when, but is not failing anymore.
