### ISSUE TITLE
Sorteo certificado

### ISSUE THREAD

**Issue by mariocj89** [etcaterva/eas-frontend#192]
Un usuario nos ha pedido soportar sorteos certificados pagaods, para tener una garantia en los sorteos.

Le gustaria tambien las siguiente features:

- Poder cambiar la imagen que sale al compartir una tirada.
- Poder poner una imagen especifica en una tirada.
- Poder embeber el sorteo en su propia web.
- Disable adds.
- Tener soporte.

Quizas podamos ofrecer diferentes niveles de sorteo certificado.

**Comment by mariocj89** [comment]
Ya tenemos una cuenta de paypal configurada para ofrecer este servicio.

**Comment by dnaranjo89** [comment]
done
