### ISSUE TITLE
FB raffles generate around 8 GET requests per second

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-frontend#197]
This is too much, we get spammed just by having a raffle open.

**Comment by palvarez89** [comment]
Not limited to FB raffles I believe. Any scheduled raffles showing the countdown.

**Comment by dnaranjo89** [comment]
fixed on e3d32bef8b3027904eed8b7bfcad24698b5010d

**Comment by palvarez89** [comment]
yyyyyyay!
