### ISSUE TITLE
Add a sitemap

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/eas-frontend#36]
I'm not sure whether we really need it but I believe they are useful for SEO in websites that don't have many external links (it may be our case because of new urls?)
Sitemaps apparently need absolute paths, so we need a way to build them dynamically based on the domain.

**Comment by dnaranjo89** [comment]
This is not a priority until we kill eas2

**Comment by mariocj89** [comment]
I guess this is a priority now 🤣

**Comment by dnaranjo89** [comment]
This is done already 👌
