### ISSUE TITLE
Setup redirect for groups

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/eas-frontend#51]
# What?
Get rid of the old ugly URLs. We don't want to break all existing links so we need to set Redirects before.

# How?
We need to setup redirects (301) for the following pages.
Old: `/draw/new/groups`
New: `/groups`

Old: `/draw/new/groups/shared`
New: `/groups/public`

- [x] New URLs are ready in eas3: https://github.com/etcaterva/eas-frontend/commit/52f67267ebddc85349474a91ffc95e6876492055
- [x] In Nginx: Route the new URL to eas3
- [x] In Nginx: Setup the redirects below
- [x] In eas2: homepage is linking to new URL: https://github.com/etcaterva/echaloasuerte/pull/719

**Comment by palvarez89** [comment]
- The routing of `/groups/*` was already in place
- The redirects implemented in: b8098eac56597d1d58f6dda3a13ab729620c9b5c

You shoul also add to this list: Change link in "Genera grupos certificados" button.
