### ISSUE TITLE
Scroll after toss

### ISSUE THREAD

**Issue by mariocj89** [etcaterva/eas-frontend#60]
When a user tosses a draw, they need to scroll themselves, which might be missed if the results do not feed the screen. Should we scroll in such a situation?

**Comment by dnaranjo89** [comment]
I've started this ([this branch](https://github.com/etcaterva/eas-frontend/tree/scroll_to_results) contains some tests I did). It need to update a dependency that was already bumped in https://github.com/etcaterva/eas-frontend/pull/57. So I'll wait for this one to be merged
