### ISSUE TITLE
Auto scroll to results happens before the results are ready

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/eas-frontend#75]
The result of this timing issue is that the page will sometimes not scroll to the results.

**Comment by dnaranjo89** [comment]
How can I reproduce this? It works fine on my phone
![ezgif-4-12c77f843580](https://user-images.githubusercontent.com/9324508/57941850-4a80da80-78d0-11e9-8aca-7a7e2c6ac9c8.gif)

**Comment by palvarez89** [comment]
Laptop screen. Put 10 different options, and make 10 groups. It will not scroll as you are already at the end of the page, and then show the groups.
