### ISSUE TITLE
Implement dice draw

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/eas-frontend#8]
# Alternatives:
## Simple JS and CSS:
- https://github.com/chukwumaijem/roll-a-die [codepen](https://codepen.io/chukwuma-ezumezu/pen/qYKOGW)

## WebGL, threejs, cannonjs and stuff:
- https://github.com/byWulf ([see reference site](http://a.teall.info/dice/))

## Three fiber
https://github.com/react-spring/react-three-fiber ([see example](https://codesandbox.io/embed/r3f-cannon-physics-nr84m))

## Others
- (bad) http://www.adam-tyler.com/react-dice-complete/
 - (nice, but not easy to pull in) https://github.com/jakehockey10/dice-roller (see [website](https://jakehockey10.github.io/dice-roller/roll))

**Comment by mariocj89** [comment]
Released
